services:
  - type: web
    name: cyberlearn-ai
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: "sh -c 'flask seed-db; gunicorn run:app'"
    envVars:
      - key: FLASK_APP
        value: run.py
      - key: FLASK_CONFIG
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
