"""topic user_id eklendi

Revision ID: 294ba7f0547e
Revises: f1abdb670357
Create Date: 2026-05-24 23:28:04.794336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '294ba7f0547e'
down_revision = 'f1abdb670357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_topic_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_constraint('fk_topic_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
