"""UserProgress wrong_count ve attempts eklendi

Revision ID: 69ba99c9a83f
Revises: 294ba7f0547e
Create Date: 2026-05-27 02:23:56.609569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ba99c9a83f'
down_revision = '294ba7f0547e'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wrong_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('attempts', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.drop_column('attempts')
        batch_op.drop_column('wrong_count')

    # ### end Alembic commands ###
